### ISSUE TITLE
使用 Release v0.1.0 绿色版无法下载预编译程序

### ISSUE THREAD

**Issue by ilharp** [WankkoRee/eaio#2]
使用 [Release v0.1.0](https://github.com/WankkoRee/eaio/releases/tag/v0.1.0) 绿色版下载预编译程序失败，报错如下：

```txt
> ./eaio d C 16.0.6 x64
  INFO   | 正在下载 Electron 预编译程序
  INFO   | 目标版本: electron-v16.0.6-win32-x64
  INFO   | 目标仓库: C:\.electron\16.0.6-x64
 DEBUG   | 下载地址: https://github.com/electron/electron/releases/download/v16.0.6/electron-v16.0.6-win32-x64.zip
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "eaio.__main__", line 116, in main
  File "eaio.download", line 13, in download
  File "eaio.utils", line 47, in download_electron
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 486, in send
  File "urllib3.connectionpool", line 769, in urlopen
  File "urllib3.connectionpool", line 295, in _get_conn
  File "urllib3.connectionpool", line 1056, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.
```

换用 pip 安装后问题解决。是否是 Release 版本缺少了依赖所致？

**Comment by WankkoRee** [comment]
确实是缺少了ssl依赖，感谢反馈。

**Comment by helloyan** [comment]
修复了没，另外是否可以增加个链接本地python库的选项，毕竟你的应用也是做的类似功能

**Comment by WankkoRee** [comment]
在 [v0.2.0](https://github.com/WankkoRee/eaio/releases/tag/v0.2.0) 中修复，请再次尝试，如问题不再存在可关闭此 issue。

**Comment by helloyan** [comment]
λ eaio check D:\PortableProgram\Develop\Apiofx
 ERROR   | D:\.eaio\12.0.16-x64 链接仓库存在问题
  INFO   | 正在下载
 ERROR   | 网络存在问题

**Comment by helloyan** [comment]
另外是不是仓库的文件名变更了？变成.eaio了

**Comment by WankkoRee** [comment]
@helloyan

关于 Python 的包管理链接方案，作为第三方工具实现会比较麻烦，开发时容易与现有包管理工具出现不兼容的情况。这个需求实际上是包管理工具才能原生支持的功能，如 Node.js 的 [pnpm](https://pnpm.io/) 就实现了中心化安装缓存和模块依赖硬链接。在 Python 下，与 `pnpm` 比较相似的包管理工具有 [pdm](https://pdm.fming.dev/)，但是也只实现了 `pnpm` 中的中心化安装缓存，并没有实现模块依赖硬链接，如有需要可前往 [pdm-project / pdm](https://github.com/pdm-project/pdm) 发起 issue 提出需求和建议。

----

网络问题请手动使用`eaio download`命令配置**代理**或**在线仓库源**进行下载，或使用 GUI 进行配置和下载。

----

链接仓库改名在 [v0.2.0](https://github.com/WankkoRee/eaio/releases/tag/v0.2.0) 发版公告中有提及和强调。

----

请不要在 issue 中讨论当前 issue 主题不相关的内容，如有需要可另开 issue。本 issue 中与 **SSL 依赖缺失** 主题无关的内容将不再回复。
