### ISSUE TITLE
预编译程序文件夹内缺失文件时 link 操作会导致原程序文件丢失

### ISSUE THREAD

**Issue by ilharp** [WankkoRee/eaio#3]
在 `C:\.electron\16.0.6-x64` 文件夹为空时，执行 link 操作：

```txt
> eaio l "C:\Users\Il Harper\AppData\Local\Programs\PicGo"
 DEBUG   | 解析 PicGo.exe 文件头
 DEBUG   | PicGo.exe 的 electron 版本为 16.0.6，CPU 架构为 x64
 DEBUG   | 解析 Uninstall PicGo.exe 文件头
 DEBUG   | Uninstall PicGo.exe 没有 IMAGE_DIRECTORY_ENTRY_EXPORT
  INFO   | 应用入口: PicGo.exe, Electron 版本: 16.0.6, CPU 架构: x64
  INFO   | 预期链接到 C:\.electron\16.0.6-x64
  INFO   | chrome_100_percent.pak 不存在可链接文件
  ...
  INFO   | locales\zh-TW.pak 不存在可链接文件
  INFO   | 将 electron.exe 链接到 PicGo.exe
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\eaio.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\eaio\__main__.py", line 107, in main
    link(Path(args.path))
  File "C:\ProgramData\Miniconda3\lib\site-packages\eaio\link.py", line 41, in link
    create_link(repo, 'electron.exe', target, relative_name)
  File "C:\ProgramData\Miniconda3\lib\site-packages\eaio\link.py", line 12, in create_link
    target.joinpath(target_name).hardlink_to(repo.joinpath(repo_name))
  File "C:\ProgramData\Miniconda3\lib\pathlib.py", line 1263, in hardlink_to
    self._accessor.link(target, self)
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。: 'C:\\.electron\\16.0.6-x64\\electron.exe' -> 'C:\\Users\\Il Harper\\AppData\\Local\\Programs\\PicGo\\PicGo.exe'
```

此时原程序文件夹内 `PicGo.exe` 已不存在。

预编译程序未下载时，link 操作会尝试下载预编译程序；如果下载失败则会保留空文件夹。再次执行 link 操作就会出现此情况。推荐在进行硬链接前先检查预编译程序文件夹内的相关文件是否存在。

**Comment by WankkoRee** [comment]
链接前检查链接仓库的可用性会在下个版本加上，感谢反馈。

**Comment by WankkoRee** [comment]
在 [v0.2.0](https://github.com/WankkoRee/eaio/releases/tag/v0.2.0) 中修复，请再次尝试，如问题不再存在可关闭此 issue。
